### ISSUE TITLE
Uncaught TypeError: _planetmint_driver__WEBPACK_IMPORTED_MODULE_9__.Connection is not a constructor

### ISSUE THREAD

**Issue by sophie-pan** [planetmint/planetmint-driver-ts#22]
# Pre-condition
`npm install planetmint-driver` did not work (following README). So i searched for `planetmint` on `npmjs` and i found [@planetmint/driver](https://www.npmjs.com/package/@planetmint/driver).
```bash
npm i @planetmint/driver #version installed: 0.2.1
```
Since i couldn't trust the outdated README, i followed the [official docs](https://docs.planetmint.io/introduction/quickstart) and adapted it to javascript. It mentionned that we can use IPDB testnet.
```
#.env
REACT_APP_BLOCKCHAIN_URL="https://test.ipdb.io"
```

# Main flow 
Tried to connect to IPDB testnet, but failed.
```js
import driver from "@planetmint/driver";
const conn = new driver.Connection(process.env.REACT_APP_BLOCKCHAIN_URL);
```
```
Uncaught TypeError: _planetmint_driver__WEBPACK_IMPORTED_MODULE_9__.Connection is not a constructor
    at ./src/App.js (App.js:19:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (reducer.js:8:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

# Solution
`Connection` is not an object of `driver` but `planetmint-driver` which is in `driver`.
```js
const conn = new driver["planetmint-driver"].Connection(process.env.REACT_APP_BLOCKCHAIN_URL);
```

```js
console.log("driver", driver)
```
<img width="534" alt="image" src="https://github.com/planetmint/planetmint-driver-ts/assets/75846673/f38cfc5b-1f3f-41c1-b318-f97d55e74ced">

# checkboxes:
- [x] documentation at:
  - [x] https://github.com/planetmint/planetmint-driver-ts#installation-and-usage
  - [x] https://www.npmjs.com/package/@planetmint/driver
  - [x] https://docs.planetmint.io/introduction/quickstart

First time writing an issue, i don't really what other info i should give. sorry for the inconvenience...

**Comment by sophie-pan** [comment]
Ok, i was able to make it work. The issue was how i accessed `Connection`. It should be called like that:
```js
const conn =  new driver["bigchaindb-driver"].Connection(process.env.REACT_APP_BLOCKCHAIN_URL);
```

I didn't consider this since the IDE pointed to `Connection` source code without issue.
Well i hope this can help others.

**Comment by sophie-pan** [comment]
Ok, i was able to make it work. The issue was how i accessed `Connection`. It should be called like that:
```js
const conn =  new driver["bigchaindb-driver"].Connection(process.env.REACT_APP_BLOCKCHAIN_URL);
```

I didn't consider this since the IDE pointed to `Connection` source code without issue.
Well i hope this can help others.
